on:
  pull_request: {}
  push:
    branches: main

name: CI

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        RUST:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1
        with:
          toolchain: ${{ matrix.RUST }}
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --workspace --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        RUST:
          - stable
          - beta
          - nightly
          # MSRV
          - "1.85"
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1
        with:
          toolchain: ${{ matrix.RUST }}

      - run: cargo test --locked --workspace --all-targets
